### ISSUE TITLE
Gostei, mas...

### ISSUE THREAD

**Issue by Meiguins** [tiago-aguiar/terminator-theme#1]
Ficou bem bonito, mas acho que ficaria melhor se diferenciasse mais as palavras-chaves de outras palavras

**Comment by tiago-aguiar** [comment]
Tá lá, feito ^^
Diferenciando mais as palavras-chaves
![](https://raw.githubusercontent.com/tiago-aguiar/terminator-theme/main/screenshots/2.png)
